name: CI

on: [push, pull_request]

jobs:
  test-src:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v4
        with:
            lfs: 'true'
      - uses: oven-sh/setup-bun@v1
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: make setup
      - run: make test-spec-bun-with-coverage
      - run: make test-spec-dom-with-coverage
      - run: make lint-ci
      - run: make test-src-tsc
      - run: make test-src-import-restrictions
      - run: make test-src-scripts-consistency
      - run: make format # note: not in `test-src` in `package.json`, only in CI
      - run: make clean

  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v4
        with:
            lfs: 'true'
      - uses: oven-sh/setup-bun@v1
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: make setup
      - run: make build-lib-js
      - run: make build-bin
      - run: make build-lib-types
      - run: make build-sites
      - run: make build-site-docs
      - run: make clean

  test-dist:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v4
        with:
            lfs: 'true'
      - uses: oven-sh/setup-bun@v1
      - name: Use `node` v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: make setup
      - run: make build-lib-js
      - run: make test-dist-lib-node-import
      - run: make test-dist-lib-node-scramble
      - run: make test-dist-lib-bun-scramble-all-events
      - run: make test-dist-lib-perf
      - run: make test-dist-lib-plain-esbuild-compat
      - run: make test-dist-lib-build-size
      - run: make build-bin
      - run: make test-dist-bin
      - run: make build-sites
      - run: make test-dist-sites-experiments
      - run: make clean

  test-make-test-fast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            lfs: 'true'
      - uses: oven-sh/setup-bun@v1
      - run: make setup
      - name: Set up `node`
        uses: actions/setup-node@v4
        with:
          node-version: v19
      - run: time make test-fast
